version: '3.8'

services:
 database:
  platform: linux/x86_64
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=pumpkin
  - MYSQL_DATABASE=dev
  volumes:
  - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  restart: always

volumes:
  mysql:
  mysql_config: